--PENDIENTE POR AÑADIR LOS VALORES CORRESPONDIENTES 
--Acuerdate que para meter los strings, hay que hacerlo con comillas simples ''
INSERT INTO USERS (USER_ID, VEHICLE_ID, AGE, REGION, IDENTIFICATION) VALUES (1,1,18,'Madrid', '06679111A');
INSERT INTO USERS (USER_ID, VEHICLE_ID, AGE, REGION, IDENTIFICATION) VALUES (2,2,19, 'Murcia', '36691256B');
INSERT INTO USERS (USER_ID, VEHICLE_ID, AGE, REGION, IDENTIFICATION) VALUES (3,3,25, 'Jerez de la Frontera', 'PALJX1028A');
--
--INSERT INTO HOSTS (USER_ID, HOST_ID, VEHICLE_ID, CHARGER_LOCATION, HOURLY_RATE, RATING, NUMBER_HOSTED, IDENTIFICATION) VALUES ();
--INSERT INTO HOSTS (USER_ID, HOST_ID, VEHICLE_ID, CHARGER_LOCATION, HOURLY_RATE, RATING, NUMBER_HOSTED, IDENTIFICATION) VALUES ();
--INSERT INTO HOSTS (USER_ID, HOST_ID, VEHICLE_ID, CHARGER_LOCATION, HOURLY_RATE, RATING, NUMBER_HOSTED, IDENTIFICATION) VALUES ();
--
--INSERT INTO VEHICLES (USER_ID, VEHICLE_ID, ELECTRIC, MODEL, LICENSE_PLATE, WATTAGE) VALUES ();
--INSERT INTO VEHICLES (USER_ID, VEHICLE_ID, ELECTRIC, MODEL, LICENSE_PLATE, WATTAGE) VALUES ();
--INSERT INTO VEHICLES (USER_ID, VEHICLE_ID, ELECTRIC, MODEL, LICENSE_PLATE, WATTAGE) VALUES ();
--
--INSERT INTO NEWSLETTER_MEMBERS (USER_ID, E_MAIL) VALUES ();
--INSERT INTO NEWSLETTER_MEMBERS (USER_ID, E_MAIL) VALUES ();
--INSERT INTO NEWSLETTER_MEMBERS (USER_ID, E_MAIL) VALUES ();
--
--INSERT INTO CHARGERS (USER_ID, CHARGER_ID, CHARGER_NAME, LATITUDE, LONGITUDE, POWER) VALUES ();
--INSERT INTO CHARGERS (USER_ID, CHARGER_ID, CHARGER_NAME, LATITUDE, LONGITUDE, POWER) VALUES ();
--INSERT INTO CHARGERS (USER_ID, CHARGER_ID, CHARGER_NAME, LATITUDE, LONGITUDE, POWER) VALUES ();
--
--INSERT INTO RESERVATIONS (USER_ID, RESERVATION_ID, HOST_ID, PRICE, CHARGER_LOCATION, RESERVATION_DATE, RESERVATION_HOUR) VALUES ();
--INSERT INTO RESERVATIONS (USER_ID, RESERVATION_ID, HOST_ID, PRICE, CHARGER_LOCATION, RESERVATION_DATE, RESERVATION_HOUR) VALUES ();
--INSERT INTO RESERVATIONS (USER_ID, RESERVATION_ID, HOST_ID, PRICE, CHARGER_LOCATION, RESERVATION_DATE, RESERVATION_HOUR) VALUES ();

