--PENDIENTE POR AÑADIR LOS VALORES CORRESPONDIENTES 
--Acuerdate que para meter los strings, hay que hacerlo con comillas simples ''

INSERT INTO USERS (USER_NAME, SURNAME, E_MAIL, PASSWORD, DOB) VALUES ('Luis','Bueno','lb@mail.es', 'CoNtRaSeNiA', '2000-11-15');
INSERT INTO USERS (USER_NAME, SURNAME, E_MAIL, PASSWORD, DOB) VALUES ('Yago','Tobio','saltyagi@mail.uk', 'CoNtRaSeNiA','2000-11-15');
INSERT INTO USERS (USER_NAME, SURNAME, E_MAIL, PASSWORD, DOB) VALUES ('Luis','Bueno','lb@mail.es', 'CoNtRaSeNiA','2000-11-15');

INSERT INTO HOSTS (USER_ID, HOURLY_RATE, NUMBER_HOSTED, IDENTIFICATION) VALUES(1, '15.5', 2, '06679111A');
INSERT INTO HOSTS (USER_ID, HOURLY_RATE, NUMBER_HOSTED, IDENTIFICATION) VALUES(2, '7.5', 3, 'UKELELE');
INSERT INTO HOSTS (USER_ID, HOURLY_RATE, NUMBER_HOSTED, IDENTIFICATION) VALUES(3, '10', 4, 'Este pasaporte es falso');

INSERT INTO VEHICLES (USER_ID, VEHICLE_ID, ELECTRIC, MODEL, LICENSE_PLATE, WATTAGE) VALUES (1,1,TRUE,'Toyota','12345J',1800000);
INSERT INTO VEHICLES (USER_ID, VEHICLE_ID, ELECTRIC, MODEL, LICENSE_PLATE, WATTAGE) VALUES (1,2,FALSE,'Kia','66666K',100);
INSERT INTO VEHICLES (USER_ID, VEHICLE_ID, ELECTRIC, MODEL, LICENSE_PLATE, WATTAGE) VALUES (2,3,TRUE,'Mercedes','97987P',9999);

INSERT INTO NEWSLETTER_MEMBERS (E_MAIL) VALUES ('ytobio66@gmail.com');
INSERT INTO NEWSLETTER_MEMBERS (E_MAIL) VALUES ('jantoniobreñamoral@gmail.com');


INSERT INTO CHARGERS (USER_ID, CHARGER_ID, LATITUDE, LONGITUDE, CHARGER_TYPE) VALUES (1,1,'40.4168','3.7038','Type 1');
INSERT INTO CHARGERS (USER_ID, CHARGER_ID, LATITUDE, LONGITUDE, CHARGER_TYPE) VALUES (2,2,'48.8566','2.3522','Type 2');
INSERT INTO CHARGERS (USER_ID, CHARGER_ID, LATITUDE, LONGITUDE, CHARGER_TYPE) VALUES (3,3,'51.5072','0.1276','Standard');
--
--INSERT INTO RESERVATIONS (USER_ID, RESERVATION_ID, HOST_ID, PRICE, CHARGER_LOCATION, RESERVATION_DATE, RESERVATION_HOUR) VALUES ();
--INSERT INTO RESERVATIONS (USER_ID, RESERVATION_ID, HOST_ID, PRICE, CHARGER_LOCATION, RESERVATION_DATE, RESERVATION_HOUR) VALUES ();
--INSERT INTO RESERVATIONS (USER_ID, RESERVATION_ID, HOST_ID, PRICE, CHARGER_LOCATION, RESERVATION_DATE, RESERVATION_HOUR) VALUES ();

