--PENDIENTE POR AÑADIR LOS VALORES CORRESPONDIENTES 
--Acuerdate que para meter los strings, hay que hacerlo con comillas simples ''
INSERT INTO USERS (USER_ID, USER_NAME, SURNAME, E_MAIL, PASSWORD, DOB) VALUES (1,'Luis','Bueno','lb@mail.es', 'CoNtRaSeNiA', '2000-11-15');
INSERT INTO USERS (USER_ID, USER_NAME, SURNAME, E_MAIL, PASSWORD, DOB) VALUES (2,'Yago','Tobio','saltyagi@mail.uk', 'CoNtRaSeNiA','2000-11-15');
INSERT INTO USERS (USER_ID, USER_NAME, SURNAME, E_MAIL, PASSWORD, DOB) VALUES (3,'Luis','Bueno','lb@mail.es', 'CoNtRaSeNiA','2000-11-15');

--
--INSERT INTO HOSTS (USER_ID, HOST_ID, VEHICLE_ID, CHARGER_LOCATION, HOURLY_RATE, RATING, NUMBER_HOSTED, IDENTIFICATION) VALUES ();
--INSERT INTO HOSTS (USER_ID, HOST_ID, VEHICLE_ID, CHARGER_LOCATION, HOURLY_RATE, RATING, NUMBER_HOSTED, IDENTIFICATION) VALUES ();
--INSERT INTO HOSTS (USER_ID, HOST_ID, VEHICLE_ID, CHARGER_LOCATION, HOURLY_RATE, RATING, NUMBER_HOSTED, IDENTIFICATION) VALUES ();
--
--INSERT INTO VEHICLES (USER_ID, VEHICLE_ID, ELECTRIC, MODEL, LICENSE_PLATE, WATTAGE) VALUES ();
--INSERT INTO VEHICLES (USER_ID, VEHICLE_ID, ELECTRIC, MODEL, LICENSE_PLATE, WATTAGE) VALUES ();
--INSERT INTO VEHICLES (USER_ID, VEHICLE_ID, ELECTRIC, MODEL, LICENSE_PLATE, WATTAGE) VALUES ();
--
INSERT INTO NEWSLETTER_MEMBERS (E_MAIL) VALUES ('ytobio66@gmail.com');
INSERT INTO NEWSLETTER_MEMBERS (E_MAIL) VALUES ('jantoniobreñamoral@gmail.com');
--INSERT INTO NEWSLETTER_MEMBERS (USER_ID, E_MAIL) VALUES ();
--
--INTO CHARGERS (USER_ID, CHARGER_ID, CHARGER_NAME, LATITUDE, LONGITUDE, POWER) VALUES (1,"H","Charger1",123,456,2);
--INTO CHARGERS (USER_ID, CHARGER_ID, CHARGER_NAME, LATITUDE, LONGITUDE, POWER) VALUES (2,"I","Charger2",3,7,3);
--INTO CHARGERS (USER_ID, CHARGER_ID, CHARGER_NAME, LATITUDE, LONGITUDE, POWER) VALUES (3,"J","Charger3",4,8,4);
--
--INSERT INTO RESERVATIONS (USER_ID, RESERVATION_ID, HOST_ID, PRICE, CHARGER_LOCATION, RESERVATION_DATE, RESERVATION_HOUR) VALUES ();
--INSERT INTO RESERVATIONS (USER_ID, RESERVATION_ID, HOST_ID, PRICE, CHARGER_LOCATION, RESERVATION_DATE, RESERVATION_HOUR) VALUES ();
--INSERT INTO RESERVATIONS (USER_ID, RESERVATION_ID, HOST_ID, PRICE, CHARGER_LOCATION, RESERVATION_DATE, RESERVATION_HOUR) VALUES ();

